version: '3.4'

services:
  python-fuzzing-book:
    image: python-fuzzing-book
    container_name: fuzzing-book
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5678:5678
    volumes:
      - ./code:/app/code
